# Linear Algebra

### 1. Write a NumPy program to compute the multiplication of two given matrixes.

In [4]:
import numpy as np 
m1=np.array([[1,2],[3,4]])
m2=np.array([[5,6],[7,8]])
print(m1)
print(m2)
print(np.dot(m1,m2))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


### 2. Write a NumPy program to compute the outer product of two given vectors.

In [6]:
v1 = [[1, 2], [3, 4]]
v2 = [[5, 6], [7, 8]]
result=np.outer(v1,v2)
result

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

### 3. Write a NumPy program to compute the cross product of two given vectors.

In [8]:
result1=np.cross(v1,v2)
result2=np.cross(v2,v1)
print(f"{result1}\n{result2}")

[-4 -4]
[4 4]


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18456\2976099717.py:1: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  result1=np.cross(v1,v2)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18456\2976099717.py:2: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  result2=np.cross(v2,v1)


### 4. Write a NumPy program to compute the determinant of a given square array.

In [10]:
arr=np.array([[1,2],[3,4]])
# linear algebra
print(np.linalg.det(arr))


-2.0000000000000004


### 5. Write a NumPy program to evaluate Einstein's summation convention of two given multidimensional arrays.

In [12]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
# mk row-column arr1 kn row-column arr2
# shared k summation
print(np.einsum("mk,kn",arr1,arr2))

[[ 7 10]
 [15 22]]


### 6. Write a NumPy program to compute the inner product of vectors for 1-D arrays (without complex conjugation) and in higher dimension

In [13]:
v1=[1,2,3]
v2=[1,2,3]
print(np.inner(v1,v2))

14


### 7. Write a NumPy program to compute the eigenvalues and right eigenvectors of a given square array.

In [14]:
arr=np.array([[1,2],[3,4]])
print(np.linalg.eig(arr))

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


### 8. Write a NumPy program to compute the Kronecker product of two given mulitdimension arrays.

In [15]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
print(np.kron(arr1,arr2))

[[ 1  2  2  4]
 [ 3  4  6  8]
 [ 3  6  4  8]
 [ 9 12 12 16]]


### 9. Write a NumPy program to compute the condition number of a given matrix.


In [16]:
m1=np.array([[1,2],[3,4]])
print(np.linalg.cond(m1))

14.933034373659268


### 10. Write a NumPy program to find a matrix or vector norm.

In [17]:
print(np.linalg.norm(m1))

5.477225575051661


### 11. Write a NumPy program to compute the determinant of an array.

In [19]:
arr=np.array([[2,2],[4,4]])
print(np.linalg.det(arr))             

0.0


### 12. Write a NumPy program to compute the inverse of a given matrix.

In [20]:
m1=np.array([[2,6,5],[4,2,3],[2,9,4]])
print(np.linalg.inv(m1))

[[-0.30645161  0.33870968  0.12903226]
 [-0.16129032 -0.03225806  0.22580645]
 [ 0.51612903 -0.09677419 -0.32258065]]


### 13. Write a NumPy program to calculate the QR decomposition of a given matrix

In [21]:
print(np.linalg.qr(m1))

QRResult(Q=array([[-0.40824829,  0.36326777, -0.83747828],
       [-0.81649658, -0.555586  ,  0.15702718],
       [-0.40824829,  0.74790423,  0.52342392]]), R=array([[-4.89897949, -7.75671752, -6.12372436],
       [ 0.        ,  7.79957264,  3.14119775],
       [ 0.        ,  0.        , -1.62261416]]))


### 14. Write a NumPy program to compute the condition number of a given matrix.

In [22]:
m1=np.array([[1,2],[3,4]])
print(np.linalg.cond(m1))

14.933034373659268


### 15. Write a NumPy program to compute the sum of the diagonal element of a given array.

In [24]:
arr=np.array([[2,2],[4,4]])
print(np.sum(np.diag(arr)))
# or 
print(np.trace(arr))

6
6


### 16. Write a NumPy program to get the lower-triangular L in the Cholesky decomposition of a given array.

In [36]:
arr=np.array([[2, 3, 10], [3, 37, -22], [10, -22, 98]],dtype='int32')
# triangular L
print(np.linalg.cholesky(arr))

[[ 1.41421356  0.          0.        ]
 [ 2.12132034  5.70087713  0.        ]
 [ 7.07106781 -6.49022934  2.4242366 ]]


### 17. Write a NumPy program to get the qr factorization of a given array.

In [39]:
arr=np.array([[14,8],[5,7]])
print(np.linalg.qr(arr))

QRResult(Q=array([[-0.94174191, -0.3363364 ],
       [-0.3363364 ,  0.94174191]]), R=array([[-14.86606875,  -9.88829007],
       [  0.        ,   3.90150221]]))


### 18. Write a NumPy program to compute the factor of a given array by Singular Value Decomposition.

### 19. Write a NumPy program to calculate the Frobenius norm and the condition number of a given array.

In [ ]:
arr = np.arange(1, 10).reshape((3, 3))
print(arr)
# frobenius norm
print(np.linalg.norm(arr, 'fro')) 
print(np.linalg.cond(arr, 'fro')) 