### 1. Write a NumPy program to generate five random numbers from the normal distribution.

In [3]:
import numpy as np

In [4]:
print(np.random.normal(0,10,5))

[-0.17382758 -6.98735504 12.17168184 -6.43799464  1.97851925]


### 2. Write a NumPy program to generate six random integers between 10 and 30.

In [5]:
print(np.random.randint(10,30,6))

[25 18 14 22 15 10]


### 3. Write a NumPy program to create a 3x3x3 array with random values.

In [6]:
print(np.random.randint(1,100,27).reshape(3,3,3))

[[[15  7 88]
  [48 90 56]
  [ 5 81 34]]

 [[ 5 64 77]
  [93 82 83]
  [31 48 58]]

 [[52 59 45]
  [68 49  2]
  [49 50  9]]]


### 4. Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [7]:
arr=np.random.randint(1,100,25).reshape(5,5)
print(f"{arr}\n{np.min(arr)}\n{np.max(arr)}")

[[23 92  6 26 48]
 [81 54 27 46 40]
 [20 99 15 92 73]
 [10  4 43  6 85]
 [22 77 71 23 10]]
4
99


### 5. Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [9]:
arr=np.random.randint(1,30,40).reshape(10,4)
print(arr)
arr2=arr[[0,1,2,3,4],:]
print('='*13)
print(arr2)

[[27 29 27 25]
 [29  5 27  3]
 [24 13 20 26]
 [10 27 18 13]
 [ 6  1 23 19]
 [ 1 20 22 19]
 [12  5 27 18]
 [27 27 24 17]
 [24 23  3 11]
 [14  8  7 23]]
[[27 29 27 25]
 [29  5 27  3]
 [24 13 20 26]
 [10 27 18 13]
 [ 6  1 23 19]]


### 6. Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).

In [11]:
arr=np.array([1,2,3,4])
np.random.shuffle(arr)
print(arr)

[3 2 4 1]


### 7. Write a NumPy program to normalize a 3x3 random matrix.

In [13]:
m=np.arange(1,10).reshape(3,3)
print(m)
m = (m - m.min()) / (m.max() - m.min())
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]


### 8. Write a NumPy program to create a random vector of size 10 and sort it.

In [16]:
vec=np.random.rand(10)
print(vec)
vec=np.sort(vec)
print(vec)

[0.86104889 0.58191703 0.94600207 0.76035885 0.73592804 0.65819073
 0.11078823 0.49110753 0.88636358 0.35644986]
[0.11078823 0.35644986 0.49110753 0.58191703 0.65819073 0.73592804
 0.76035885 0.86104889 0.88636358 0.94600207]


### 9. Write a NumPy program to find the nearest value from a given value in an array.

### 10. Write a NumPy program to check two random arrays are equal or not.

In [27]:
arr1=np.random.randint(0,2,4)
arr2=np.random.randint(0,2,4)
print(f"{arr1} \n{arr2}") 
print(np.allclose(arr1,arr2))

[0 1 0 1] 
[0 1 0 1]
True


### 11. Write a NumPy program to create random vector of size 15 and replace the maximum value by -1.

In [33]:
vec=np.random.randint(0,16,15)
print(vec)
vec[vec.argmax()]=-1
print(vec)

[ 2 10 10  7  7  9  4  8 15  9  7 10  9 12 14]
[ 2 10 10  7  7  9  4  8 -1  9  7 10  9 12 14]


### 13. Write a NumPy program to find the most frequent value in an array.


In [38]:
vec = np.random.randint(0, 10,20).reshape(10,2)
print(vec)
vec=vec.flatten()
print(vec)
frequent = np.bincount(vec).argmax()
print(frequent)   

[[8 6]
 [7 0]
 [0 6]
 [4 5]
 [1 3]
 [4 6]
 [5 6]
 [2 9]
 [6 0]
 [6 2]]
[8 6 7 0 0 6 4 5 1 3 4 6 5 6 2 9 6 0 6 2]
6
