### 1. Write a Numpy program to get the Numpy version and show the Numpy build configuration.

In [43]:
import numpy as np
print(np.__version__)
print(np.show_config)

2.0.0
<function show at 0x00000224CB907420>


### 2. Write a NumPy program to get help with the add function.

In [4]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

### 3. Write a NumPy program to test whether none of the elements of a given array are zero.

In [9]:
arr=np.array([1,2,3,4])
if np.all(arr)==True:
    print("no zeros")


no zero


### 4. Write a NumPy program to test if any of the elements of a given array are non-zero.

In [15]:
arr=np.array([0,0,0,0,0,0,7])
if np.any(arr)==True:
    print("non-zero found in the array")
else:
    print("all zeros")

non-zero found in the array


### 5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a number).

In [28]:
arr1=np.array([1,7,np.nan,np.inf])
print(arr1)
print(np.isfinite(arr1))


[ 1.  7. nan inf]
[ True  True False False]


### 6. Write a NumPy program to test elements-wise for positive or negative infinity.


In [31]:
arr=np.array([-np.inf,-1,0,1,np.inf])
print("Element-wise positive infinity check:",np.isposinf(arr))
print("Element-wise negative infinity check:",np.isneginf(arr))

Element-wise positive infinity check: [False False False False  True]
Element-wise negative infinity check: [ True False False False False]


### 7. Write a NumPy program to test element-wise for NaN of a given array.

In [32]:
arr=np.array([1,2,np.nan])
print(np.isnan(arr))

[False False  True]


### 8. Write a NumPy program to test element-wise for complex numbers, real numbers in a given array. Also test if a given number is of a scalar type or not.

In [42]:
arr=np.array([1,2,3j,1.3,2j])
print(np.iscomplex(arr))
print(np.isreal(arr))
print(np.isscalar(7.7))
print(np.isscalar([7.7]))

[False False  True False  True]
[ True  True False  True False]
True
False


### 9. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [55]:
arr1=np.array([1,2,3,4])
arr2=np.array([1,2,3,4])
arr3=np.array([1e10,1e-8])
arr4=np.array([1.00001e10,1e-9])
arr5=np.array([5,1,4,4])
print(np.allclose(arr1,arr2))
print(np.allclose(arr1,arr5))
print(np.allclose(arr3,arr4))

True
False
True


### 10. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [56]:
print(np.greater(arr1,arr5))
print(np.greater_equal(arr1,arr5))
print(np.less(arr1,arr5))
print(np.less_equal(arr1,arr5))

[False  True False False]
[False  True False  True]
[ True False  True False]
[ True False  True  True]


### 11. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [58]:
print(np.equal(arr1,arr2))
print(np.allclose(arr3,arr4))

[ True  True  True  True]
True


### 12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [60]:
arr=np.array([1,7,13,105])
print(f"array size = {np.size(arr)}")

array size = 4


### 13. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives

In [64]:
arr=np.array([np.zeros(10),np.ones(10),np.ones(10)*5],dtype="int")
print(arr)

[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [5 5 5 5 5 5 5 5 5 5]]


### 14. Write a NumPy program to create an array of integers from 30 to 70.

In [69]:
arr=np.arange(30,71)
print(arr)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


### 15.Write a NumPy program to create an array of all even integers from 30 to 70.

In [70]:
arr=np.arange(30,71,2)
print(arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


### 16. Write a NumPy program to create a 3x3 identity matrix.

In [81]:
# method 1
i =np.eye(3,3,dtype="int8")
print(i)
# method 2 
print("="*12)
i=np.identity(3,dtype="int")
print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


### 17. Write a NumPy program to generate a random number between 0 and 1.

In [106]:
number=np.random.normal(0,1,1)
print(number)

[0.85255263]


### 18. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [108]:
numbers=np.random.normal(0,1,15)
print(numbers)

[ 1.83143205  0.58157892  1.15870422  1.63584723  0.30902248  0.79644436
 -0.31053983  0.5608433   0.67252421 -0.6779174   0.58852916  1.12319999
  0.29815757 -0.39333766 -0.54064224]


### 19. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [112]:
vec=np.arange(15,55)
print(vec[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


### 20. Write a NumPy program to create a 3X4 array and iterate over it.

In [117]:
arr=np.arange(1,13).reshape(3,4)
print(arr)
# iterate
for i in np.nditer(arr):
    print(i ,end=" ")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1 2 3 4 5 6 7 8 9 10 11 12 

### 21. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [133]:
vec=np.linspace(5, 50, 10)
print(vec)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


### 22. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [140]:
vec=np.arange(21)
vec[(vec>=9) & (vec<=15)]*=-1
print(vec)  

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


### 23. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.


In [145]:
vec=np.random.randint(0,10,5)
print(vec)


[0 2 6 6 7]


### 24. Write a NumPy program to multiply the values of two given vectors.

In [146]:
vec = np.arange(1,5)
vec2 = np.arange(5,10)
print(vec*vec)

[ 1  4  9 16]


### 25. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [148]:
matrix = np.arange(10,22).reshape(3,4)
print(matrix)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


### 26. Write a NumPy program to find the number of rows and columns in a given matrix.

In [153]:
print(f"rows = {len(matrix)}")
print(f"columns = {len(matrix[0])}")
# or 
print(matrix.shape)

rows = 3
columns = 4
(3, 4)


### 27. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal elements are 1, the rest are 0.

In [193]:
i = np.identity(3,dtype="int")
print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### 28. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [169]:
matrix = np.ones((10,10),dtype='int')
matrix[1:-1,1:-1]=0
print(matrix)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


### 29. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [190]:
matrix=np.zeros((5,5),dtype='int')
#for i in range(0,5):
#   matrix[i,i]=i+1
matrix=np.diag([1,2,3,4,5])
print(matrix)
#print(np.diag(matrix))
print(np.diagonal(matrix))


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
[1 2 3 4 5]


### 30. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [192]:
i =np.identity(4,dtype='int8')
# i=1-i change 1 zeros and zeros ones
i=1-i
print(i)

[[0 1 1 1]
 [1 0 1 1]
 [1 1 0 1]
 [1 1 1 0]]


### 31. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

In [6]:
m=np.arange(1,28).reshape(3,3,3)
print(m)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


### 32. Write a NumPy program to compute the sum of all elements, the sum of each column and the sum of each row in a given array.

In [15]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print('='*15)
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]


### 33. Write a NumPy program to compute the inner product of two given vectors.

In [32]:
vec1=np.array([2,3])
vec2=np.array([4,5])
print(np.dot(vec1,vec2))


23


### 34. Write a NumPy program to add a vector to each row of a given matrix.

In [42]:
m=np.array([[1,2],[3,4],[5,6],[7,8]])
v=np.array([1,1])
m_new=m+v
print(m)
print('-'*13)
print(m_new)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
-------------
[[2 3]
 [4 5]
 [6 7]
 [8 9]]


### 35,36. Write a NumPy program to save a given array to a binary file .

In [49]:
arr= np.array([1, 2, 3, 4, 5])
np.save('array.npy', arr)
loaded_array = np.load('array.npy')
print(loaded_array)

[1 2 3 4 5]


### 37. Write a NumPy program to save a given array to a text file and load it.

In [48]:
arr = np.arange(20).reshape(4,5)
np.savetxt('array.txt',arr)
loaded= np.loadtxt('array.txt')
print(loaded)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]


### 38. Write a NumPy program to convert a given array into bytes, and load it as an array.

In [50]:
arr_bytes=arr.tobytes()
arr_load=np.frombuffer(arr_bytes,dtype=arr.dtype)
print(arr)
print(arr_bytes)
print(arr_load)

[1 2 3 4 5]
b'\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00'
[1 2 3 4 5]


### 39. Write a NumPy program to convert a given list into an array, then again convert it into a list. Check initial list and final list are equal or not.

In [54]:
l1=[[1,2,3],[4,5,6]]
arr=np.array(l1)
l2=arr.tolist()
print(arr==l2)

[[ True  True  True]
 [ True  True  True]]


### 43. Write a NumPy program to find missing data in a given array.

In [56]:
arr = np.array([[1,2,np.nan],
               [2,3,4],
               [5,np.nan,7]])
print(arr)
print(np.isnan(arr))

[[ 1.  2. nan]
 [ 2.  3.  4.]
 [ 5. nan  7.]]
[[False False  True]
 [False False False]
 [False  True False]]


### 44. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [57]:
arr1=np.array([1,2,3])
arr2=np.array([1,2,5])
print(arr1==arr2)

[ True  True False]


### 45. Write a NumPy program to create a one-dimensional array of single, two and three-digit numbers.

In [61]:
arr1=np.arange(0,10)
arr2=np.arange(10,100)
arr3=np.arange(100,200)
print(arr1)
print('-'*10)
print(arr2)
print('-'*10)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
----------
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
----------
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]


### 46. Write a NumPy program to create a two-dimensional array of a specified format.

In [66]:
arr=np.arange(1,51).reshape(25,2)
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]
 [25 26]
 [27 28]
 [29 30]
 [31 32]
 [33 34]
 [35 36]
 [37 38]
 [39 40]
 [41 42]
 [43 44]
 [45 46]
 [47 48]
 [49 50]]


### 47. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. Select random numbers from a uniform distribution between 0 and 1. 

In [67]:
print(np.random.rand(40))

[0.6004258  0.72600315 0.59798023 0.66304503 0.55399357 0.40215411
 0.03760096 0.21865303 0.42213418 0.70607171 0.13390359 0.39443297
 0.02050663 0.15330831 0.25117981 0.60740161 0.43825153 0.58020845
 0.28786591 0.90160125 0.82843301 0.23221287 0.55897709 0.48873276
 0.3639747  0.58845491 0.74400102 0.69333852 0.2303426  0.512163
 0.22015413 0.75164616 0.28433463 0.97879702 0.84099937 0.71313687
 0.56251509 0.88697601 0.01622132 0.91843727]


### 48. Write a NumPy program to create a two-dimensional array with shape (8,5) of random numbers. Select random numbers from a normal distribution (200,7).

In [74]:
arr=np.random.normal(7,201,40).reshape(8,5)
print(arr)

[[-381.91665559 -220.34478189  608.06895359  203.45229524 -310.98162607]
 [ 176.90912833  264.62138333 -229.14350089   -8.91073586 -353.19639738]
 [-173.00689947 -223.181072   -164.80260721  -42.33383785  124.04042615]
 [ 314.50011369  353.05382942 -183.5717031   112.5492426   -94.03664897]
 [ 153.68166223  132.29651113 -170.50263898 -144.95205396 -154.47607008]
 [  21.29594124  113.74847756 -157.17219888  174.19617317  139.07517836]
 [-381.381035   -137.65777284 -194.19601695  209.44548153   82.20033515]
 [  15.10879888 -250.16342403 -141.83744654  230.91101499   -3.45016672]]


### 49. Write a NumPy program to generate a uniform, non-uniform random sample from a given 1-D array with and without replacement.

In [86]:
print(np.random.choice(7,5))
print(np.random.choice(7,5,replace=False))
print(np.random.choice(7,5,p=[0.2, 0.3, 0, 0.1, 0.2, 0, 0.2]))

[1 4 0 6 0]
[5 1 3 6 4]
[6 1 1 3 6]


### 50. Write a NumPy program to create a 4x4 array with random values. Create an array from the said array swapping first and last rows.

In [94]:
arr=np.random.randint(0,100,16).reshape(4,4)
a=arr


In [97]:
print(a)
a[[0,-1],:] = a[[-1,0],:]
print('-'*10)
print(a)

[[63 48 77 99]
 [ 4 60 71 43]
 [27 25 35 45]
 [10 12 52 44]]
----------
[[10 12 52 44]
 [ 4 60 71 43]
 [27 25 35 45]
 [63 48 77 99]]


### 51. Write a NumPy program to create a new array of given shape (5,6) and type, filled with zeros.

In [102]:
arr=np.zeros(30,dtype='int').reshape(5,6)
print(arr)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


### 52. Write a NumPy program to sort a given array by row and column in ascending order.

In [124]:
arr=np.random.randint(1,10,9).reshape(3,3)
print(arr)


[[7 1 1]
 [9 8 5]
 [8 6 2]]


In [125]:
arr=np.sort(arr)
print(arr)
arr=np.sort(arr,axis=0)
print(arr)

[[1 1 7]
 [5 8 9]
 [2 6 8]]
[[1 1 7]
 [2 6 8]
 [5 8 9]]


### 53. Write a NumPy program to extract all numbers from a given array less and greater than a specified number.

In [130]:
arr=np.random.randint(1,10,9).reshape(3,3)
print(arr)
n=int(input())
print(f"numbers bigger than {n} = {arr[arr>n]}")
x=int(input())
print(f"numbers less than {x} = {arr[arr<n]}")


[[2 3 7]
 [4 8 6]
 [6 8 2]]
numbers bigger than 5 = [7 8 6 6 8]
numbers less than 2 = [2 3 4 2]


### 54. Write a NumPy program to replace all numbers in a given array equal, less and greater than a given number

In [ ]:
nums = np.array([[5, 3, 7],
              [3, 8, 6],
              [1, 2, 9]])
print(nums)
n = 8
r = 18
print(np.where(nums == n, r, nums))
print(np.where(nums < n, r, nums))
print(np.where(nums > n, r, nums)) 

### 55. Write a NumPy program to create an array of equal shape and data type for a given array.

In [143]:
arr=np.array([[5, 3, 7],
              [3, 8, 6],
              [1, 2, 9]])
arr2=np.full_like(arr,np.random.randint(200))
print(arr2)

[[90 90 90]
 [90 90 90]
 [90 90 90]]


### 56. Write a NumPy program to create a three-dimensional array with the shape (3,5,4) and set it to a variable.

In [144]:
arr = np.random.randint(0,10,60).reshape(3,5,4)
print(arr)

[[[3 1 0 9]
  [9 2 6 7]
  [3 0 9 8]
  [0 3 6 3]
  [1 6 2 0]]

 [[3 3 4 6]
  [9 6 2 5]
  [8 0 4 0]
  [9 2 5 6]
  [4 6 8 3]]

 [[3 0 8 3]
  [6 5 7 4]
  [1 8 7 7]
  [3 6 3 5]
  [6 3 2 7]]]


### 57. Write a NumPy program to create a 4x4 array. Create an array from said array by swapping first and last, second and third columns.

In [151]:
arr = np.array([[5, 3, 7,2],
              [3, 8, 6,3],
              [6, 3, 6,0],
              [1, 2, 9,1]])
print("original array:")
print(arr)
swap_row=arr[[3,1,2,0],:]
print("row swapping:")
print(swap_row)
swap_column=swap_row[:,[0,2,1,3]]
print("column swapping:")
print(swap_column)

original array:
[[5 3 7 2]
 [3 8 6 3]
 [6 3 6 0]
 [1 2 9 1]]
row swapping:
[[1 2 9 1]
 [3 8 6 3]
 [6 3 6 0]
 [5 3 7 2]]
column swapping:
[[1 9 2 1]
 [3 6 8 3]
 [6 6 3 0]
 [5 7 3 2]]


### 58. Write a NumPy program to swap rows and columns of a given array in reverse order.

In [154]:
arr = np.array([[5, 3, 7,2],
              [3, 8, 6,3],
              [6, 3, 6,0],
              [1, 2, 9,1]])
print("original array:")
print(arr)
swap_row=arr[[3,2,1,0],:]
swap_column=swap_row[:,[3,2,1,0]]
print(f"reversed array \n{swap_column}")

original array:
[[5 3 7 2]
 [3 8 6 3]
 [6 3 6 0]
 [1 2 9 1]]
reversed array 
[[1 9 2 1]
 [0 6 3 6]
 [3 6 8 3]
 [2 7 3 5]]


### 59. Write a NumPy program to multiply two given arrays of the same size element-by-element.

In [159]:
arr=np.ones((3,3))*2
arr2=np.ones((3,3))*2
print(np.multiply(arr,arr2))

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
